---
title: "HousingMarket"
author: "CGR"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r}
Sys.setlocale("LC_ALL", "English_United States.1252")

```


## Load libraries

```{r, include=FALSE}
library(lubridate)
library(ggpubr)
library(DataExplorer)
library(readr)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(corrplot)
library(tidyverse)
library(GGally)
library(gridExtra)
library(reshape)
library(groupdata2)
library(skimr)
library(patchwork)
library(reshape)
library(sjPlot)
library(jtools)
library(zoo)
library(data.table)
library(car)
library(tseries)
library(forecast)
library(MASS)
```

## 0. Import, Clean & Merge Data

```{r}
housesales <- read.csv("kaupskra.csv", header=T, fill=T, dec=",", sep=";", fileEncoding = 'UTF-8-BOM')

# convert date column to date format
housesales$utgdag <- as.Date(housesales$utgdag, format = "%Y-%m-%d %H:%M:%OS")

housesales_c <- housesales %>% 
  mutate(einflm = as.numeric(einflm)*0.1,
         kaupverd = as.numeric(kaupverd)*1000,
         fasteignamat = as.numeric(fasteignamat)*1000,
         byggar = 2023 - byggar) %>% 
  mutate(outcome = kaupverd - fasteignamat) %>%
  dplyr::select(-c(faerslunumer, emnr, skjalanumer, fastnum, heimilisfang, heinum, svfn, sveitarfelag, thinglystdags, fepilog, lod_flm, lod_flmein, fullbuid, onothaefur_samningur)) %>%
  filter(!is.na(byggar))

colnames(housesales_c) <- c('postalcode','date',  'x', 'y', 'age', 'msq', 'type', 'outcome')

housesales_s <- subset(housesales_c, type %in% c("Fjölbýli      ", "Einbýli       ", "Sérbýli       "))

housesales_f <- filter(housesales_s, msq > 25 & msq < 200 )
housesales_g <- filter(housesales_f, outcome < 20000000 )

housesales_g <- housesales_g %>%
  mutate(outcome_m = outcome/1000000)

hist(housesales_g$msq)
tmp_med <- replicate(10000, mean(sample(housesales_g$msq, replace=T), na.rm=T))
quantile(tmp_med, 0.025)
quantile(tmp_med, 0.975)
hist(tmp_med)

#bootstrapping
tmp_med <- replicate(10000, mean(sample(housesales_g$outcome, replace=T), na.rm=T))
quantile(tmp_med, 0.025)
quantile(tmp_med, 0.975)
hist(tmp_med)

head(housesales_f)

```

### Rental Price, Rental Inventory, Meters Squared, and # of bedrooms

```{r}
rentalprice <-read.csv("leiguskra.csv", header=T, fill=T, dec=",", sep=",", fileEncoding = 'UTF-8-BOM')

# convert date column to date format
rentalprice$UTGDAG <- as.Date(rentalprice$UTGDAG, format = "%Y-%m-%d %H:%M:%OS")

rentalprice_c <- rentalprice %>% 
  mutate(date = ymd(UTGDAG),
         STAERD = as.numeric(STAERD))%>%
  dplyr::select(-c(LEIGUSAMNINGUR, EMNR, SKJALNR, FASTNUM, HEINUM, HEIMILISFANG, SVFN, UTGDAG, SVEITARFELAG, THINGLYSTDAGS, DAGSFRA, DAGSTIL, FJ_HERBERGI, OTIMABUNDID, VISITALA, DAGS_VISITALA, ONOTHAEFUR_SAMNINGUR)) 

colnames(rentalprice_c) <- c('POSTALCODE', 'PRICE', 'SIZE', 'TYPE', 'date')

rentalprice_s <- subset(rentalprice_c, TYPE %in% c("Fjölbýli", "Einbýli", "Sérbýli"))

rentalprice_f <- filter(rentalprice_s, SIZE > 20 & SIZE < 200 )

head(rentalprice_f)
  
```

### Interest
```{r}
interest <-read.csv("meginvextir_US_Date.csv", header=T, fill=T, dec=",", sep=";")

interest_c <- interest %>% 
  mutate(date = ymd(date))

head(interest)
```

## full_data Datatable 

```{r}
full_data <- interest_c %>% 
  inner_join(housesales_f, by = "date") %>%
  inner_join(rentalprice_f, by = c("date")) %>%
  group_by(date) %>% 
  summarise(mean_interest_rate = mean(interest_rate), 
            mean_age = mean(age),
            mean_msq = mean(msq), 
            mean_outcome =mean(outcome), 
            mean_PRICE = mean(PRICE), 
            mean_SIZE = mean(SIZE) 
            )

fulldata_cp <- full_data %>%
  dplyr::select(-c(date, mean_outcome))

```

### Numerical data

```{r fig.height=11, fig.width=11}
full_data %>% 
  plot_histogram()
```


### Categorical 

```{r eval=FALSE, include=FALSE}
full_data %>% 
  plot_bar()
```

### Outlier Analysis
```{r}
boxplot(full_data$mean_interest_rate)
boxplot(full_data$mean_age)
boxplot(full_data$mean_msq)
boxplot(full_data$mean_outcome)
boxplot(full_data$mean_PRICE)
boxplot(full_data$mean_SIZE)
```

```{r}
fit1 <- lm(mean_outcome ~ mean_interest_rate + mean_age + mean_msq + mean_PRICE + mean_SIZE, data=full_data)
summary(fit1)
vif(fit1)
plot(fit1)
```

```{r}
full_data %>%
  plot_correlation()
```

```{r}
full_data1 <- full_data %>% 
  dplyr::rename(nuvirdi = mean_outcome)

full_data1$index2 <- c(1:length(full_data1$mean_msq))

set.seed(3689)
train <- sample_frac(full_data1, 3/4)
test <- full_data1[-train$index2,]

train_index <- c(1:length(train$mean_msq))
train$index <- train_index 
test_index <- c(1:length(test$mean_msq))
test$index <- test_index 

```

```{r}
fit_realscale <- lm(nuvirdi ~ .,data = train)
```

```{r}
diag_realscale <- fortify(fit_realscale)
preal <- ggplot(diag_realscale, aes(x=.fitted,y=nuvirdi))+geom_point()
preal <- preal + xlab("Fitted") + ylab("Nuvirdi") + labs(title = "Nuvirdi vs. fitted values")
preal
```

```{r}
#cor(train)>0.9
```

```{r}
fit <- lm(nuvirdi ~ .,data = train)
diag <- fortify(fit)
diag$.index = c(1:length(diag$.resid))
diag$.jack<-rstudent(fit)

res_sd <- summary(fit)$sigma
fit$sigma
```
```{r}
res_index <- ggplot(diag, aes(x = seq(1:length(.resid)), y = .resid)) + geom_point()
res_index <- res_index + geom_hline(yintercept = 0, col = "red", linetype = "dashed")
res_index <- res_index + geom_hline(yintercept = 2 * res_sd, col = "blue", linetype = "dashed")
res_index <- res_index + geom_hline(yintercept = -2 * res_sd, col = "blue",
linetype = "dashed") # 2 standard dev.
res_index <- res_index + geom_hline(yintercept = 3 * res_sd, col = "green",
linetype = "dashed") #3 std
res_index <- res_index + geom_hline(yintercept = -3 * res_sd, col = "green",
linetype = "dashed")
res_index <- res_index + xlab("Index") + ylab("Residuals") + labs(title = "Index plot of residuals")
res_index <- res_index + geom_text(aes(label = ifelse(abs(.resid) > 2 * res_sd,
.index, "")), hjust = -0.5, vjust = 0.4)
res_index
```
extreme residuals: 1628, 141, 1653, 785, 813, 1465, 980, 179, 802
extreme residuals: 2125, 1124, 1277, 1572, 1746, 2016, 731, 1273, 


### timeseries 
```{r}

housingmarket <- read.zoo(full_data)
timser <- as.ts(housingmarket)
```

